ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [DEMO_MVC], FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\DEMO_MVC.mdf', SIZE = 2304 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];

